### ISSUE TITLE
errors during updates flexavr and flextrack

### ISSUE THREAD

**Issue by ator1811** [daveake/HAB-Documentation#1]
Hi, I tried to update flexavr and flextrak according to the documentation. Both the update of flextrak and flexavr generates error messages. Switch is in p mode.

First flextrak:
after git pull the command chmod +x a gives an error:
pi@FLEX3:~/flextrak $ chmod +x a
chmod: cannot access 'a': No such file or directory

Second flexavr:
after git pull the command ./a gives an error:
pi@FLEX3:~/flexavr $ ./a
-bash: ./a: Permission denied

What is wrong?

**Comment by daveake** [comment]
I'll check/fix tomorrow.  The "a" script is in flexavr not flextrak.  It
needs to be made executable with chmod +x a.

**Comment by ator1811** [comment]
I think the sequence is wrong in the documentation:

chmod +x a should be written under update flexaver (with sudo?)

**Comment by daveake** [comment]
Fixed.  Thanks for letting me know.
