### ISSUE TITLE
ssdv & wiringpi installation error

### ISSUE THREAD

**Issue by ator1811** [daveake/HAB-Documentation#2]
I followed the FlexTrak Installation Manual to install Flextrak on a RPI Zero (page 51). An error occurs with the installation of ssdv and wiringpi. Are these commands still correct? I read somewhere that wiringpi is included in Raspbian.

RaspberryPi OS Lite 32-bits
Release 09-22-2022.
I performed update and upgrade. 

 pi@flextrak:~ $ sudo apt install ssdv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ssdv
pi@flextrak:~ $ 

pi@flextrak:~ $ sudo apt install wiringpi
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package wiringpi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wiringpi' has no installation candidate
pi@flextrak:~ $

**Comment by daveake** [comment]
I'll update the document.  You can see the new instructions for those in
the flextrak/STM manual.

**Comment by ator1811** [comment]
In the sofware installation section a line is missing to clone Wiring PI (page 51)

Software Installation
Run these commands:
```
sudo apt install git
sudo apt install minicom
sudo apt install avrdude
sudo apt install python3-picamera
sudo apt install python3-serial
git clone https://github.com/WiringPi/WiringPi.git <-- this line is missing in the manual
cd WiringPi
./build
cd ~
git clone https://github.com/fsphil/ssdv.git
cd ssdv
make
sudo make install
cd ~
git clone https://github.com/daveake/flexavr.git
git clone https://github.com/daveake/flextrak.git 
cd flextrak
sudo cp flextrak.ini.sample /boot/flextrak.ini 
sudo nano /etc/rc.local
```

Next to that the Firmware update section is not correct, because the flexavr.ino.hex is not downloaded with the git pull (I used scp to upload it to the RPi).

**Comment by daveake** [comment]
Line added, thanks.  Also I've put the hex file back into the flexavr repository, rather than complicate the instructions.
